// Generated by CoffeeScript 1.7.1
var DisplayBoard,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

DisplayBoard = (function() {
  function DisplayBoard(playingCards, dragCallback, clickCallback, nextGamePhase, resizeHandler) {
    this.playingCards = playingCards;
    this.dragCallback = dragCallback;
    this.clickCallback = clickCallback;
    this.nextGamePhase = nextGamePhase;
    this.resizeHandler = resizeHandler;
    this.onCardClick = __bind(this.onCardClick, this);
    this.onMouseup = __bind(this.onMouseup, this);
    this.onMousedown = __bind(this.onMousedown, this);
    this.onMousemove = __bind(this.onMousemove, this);
    this.registerListeners();
  }

  DisplayBoard.prototype.showGameState = function(gameBoard) {
    var cardFileName, cardHeight, cardId, cardWidth, colIdx, displayHeight, displayWidth, rowIdx, _i, _j, _ref, _ref1;
    displayWidth = $(window).width() - 50;
    displayHeight = $(window).height();
    cardWidth = displayWidth / gameBoard.numCols;
    cardHeight = cardWidth * 1.545;
    $('.game-board').html("");
    for (rowIdx = _i = 0, _ref = gameBoard.numRows - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; rowIdx = 0 <= _ref ? ++_i : --_i) {
      $('.game-board').append("<div class='row' id='row" + rowIdx + "'></div>");
      for (colIdx = _j = 0, _ref1 = gameBoard.numCols - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; colIdx = 0 <= _ref1 ? ++_j : --_j) {
        cardId = gameBoard.getCardId(rowIdx, colIdx);
        cardFileName = gameBoard.getCardFileName(rowIdx, colIdx);
        $("#row" + rowIdx).append("<img id='cardid" + cardId + "' class='card' width='" + cardWidth + "px' height='" + cardHeight + "px' src='cards/" + cardFileName + "'></img>");
      }
    }
    $('.card').draggable({
      cancel: "a.ui-icon",
      revert: "invalid",
      containment: "document",
      helper: "clone",
      cursor: "move"
    });
    $('.card').droppable({
      accept: ".card",
      activeClass: "ui-state-highlight",
      drop: (function(_this) {
        return function(event, ui) {
          var fromId, toId;
          fromId = _this.getIdNumFromIdAttr(ui.draggable);
          toId = _this.getIdNumFromIdAttr($(event.target));
          return _this.dragCallback(fromId, toId);
        };
      })(this)
    });
    return $('.card').click(this.onCardClick);
  };

  DisplayBoard.prototype.getIdNumFromIdAttr = function(idElem) {
    return parseInt(idElem.attr("id").slice(6));
  };

  DisplayBoard.prototype.registerListeners = function() {
    $('.game-button-next').button().click(this.nextGamePhase);
    $(window).resize(this.resizeHandler);
    return;
    document.addEventListener("mousemove", this.onMousemove, false);
    document.addEventListener("mousedown", this.onMousedown, false);
    return document.addEventListener("mouseup", this.onMouseup, false);
  };

  DisplayBoard.prototype.onMousemove = function(event) {
    return event.preventDefault();
  };

  DisplayBoard.prototype.onMousedown = function(event) {
    return event.preventDefault();
  };

  DisplayBoard.prototype.onMouseup = function(event) {
    return event.preventDefault();
  };

  DisplayBoard.prototype.onCardClick = function(event) {
    return this.clickCallback(this.getIdNumFromIdAttr($(event.target)));
  };

  return DisplayBoard;

})();
