// Generated by CoffeeScript 1.7.1
var GameBoard;

GameBoard = (function() {
  GameBoard.prototype.numRows = 4;

  GameBoard.prototype.numCols = 13;

  function GameBoard(playingCards) {
    this.playingCards = playingCards;
    this.board = [];
  }

  GameBoard.prototype.copy = function(copyFrom) {
    var boardRow, col, row, _i, _j, _ref, _ref1;
    this.board = [];
    for (row = _i = 0, _ref = this.numRows - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; row = 0 <= _ref ? ++_i : --_i) {
      boardRow = [];
      for (col = _j = 0, _ref1 = this.numCols - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; col = 0 <= _ref1 ? ++_j : --_j) {
        boardRow.push(copyFrom.board[row][col]);
      }
      this.board.push(boardRow);
    }
    return true;
  };

  GameBoard.prototype.deal = function() {
    var boardRow, col, row, _i, _j, _ref, _ref1;
    this.board = [];
    this.playingCards.startDeal();
    for (row = _i = 0, _ref = this.numRows - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; row = 0 <= _ref ? ++_i : --_i) {
      boardRow = [];
      for (col = _j = 0, _ref1 = this.numCols - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; col = 0 <= _ref1 ? ++_j : --_j) {
        boardRow.push(this.playingCards.getNextCard());
      }
      this.board.push(boardRow);
    }
    return true;
  };

  GameBoard.prototype.removeAces = function() {
    var cardId, colIdx, gapCardId, rowIdx, _i, _ref, _results;
    gapCardId = -1;
    _results = [];
    for (rowIdx = _i = 0, _ref = this.numRows - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; rowIdx = 0 <= _ref ? ++_i : --_i) {
      _results.push((function() {
        var _j, _ref1, _results1;
        _results1 = [];
        for (colIdx = _j = 0, _ref1 = this.numCols - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; colIdx = 0 <= _ref1 ? ++_j : --_j) {
          cardId = this.board[rowIdx][colIdx];
          if (this.playingCards.getCardInfo(cardId).rankIdx === this.playingCards.AceId) {
            this.board[rowIdx][colIdx] = gapCardId;
            _results1.push(gapCardId -= 1);
          } else {
            _results1.push(void 0);
          }
        }
        return _results1;
      }).call(this));
    }
    return _results;
  };

  GameBoard.prototype.redeal = function() {
    var cardId, cardInfo, colIdx, colsToRedealFrom, deck, rowIdx, suitIdxForRow, _i, _j, _k, _l, _m, _n, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7;
    colsToRedealFrom = [];
    for (rowIdx = _i = 0, _ref = this.numRows - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; rowIdx = 0 <= _ref ? ++_i : --_i) {
      suitIdxForRow = -1;
      for (colIdx = _j = 0, _ref1 = this.numCols - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; colIdx = 0 <= _ref1 ? ++_j : --_j) {
        cardId = this.board[rowIdx][colIdx];
        cardInfo = this.playingCards.getCardInfo(cardId);
        if (colIdx === 0) {
          suitIdxForRow = cardInfo.suitIdx;
        }
        if (cardInfo.isGap || cardInfo.rankIdx - 1 !== colIdx || cardInfo.suitIdx !== suitIdxForRow) {
          colsToRedealFrom.push(colIdx);
          break;
        }
      }
      console.log(colsToRedealFrom[colsToRedealFrom.length - 1]);
    }
    deck = new PlayingCards();
    deck.empty();
    for (rowIdx = _k = 0, _ref2 = this.numRows - 1; 0 <= _ref2 ? _k <= _ref2 : _k >= _ref2; rowIdx = 0 <= _ref2 ? ++_k : --_k) {
      for (colIdx = _l = _ref3 = colsToRedealFrom[rowIdx], _ref4 = this.numCols - 1; _ref3 <= _ref4 ? _l <= _ref4 : _l >= _ref4; colIdx = _ref3 <= _ref4 ? ++_l : --_l) {
        cardId = this.board[rowIdx][colIdx];
        if (cardId >= 0) {
          deck.addCard(cardId);
        }
      }
    }
    deck.shuffle();
    deck.startDeal();
    for (rowIdx = _m = 0, _ref5 = this.numRows - 1; 0 <= _ref5 ? _m <= _ref5 : _m >= _ref5; rowIdx = 0 <= _ref5 ? ++_m : --_m) {
      this.board[rowIdx][colsToRedealFrom[rowIdx]] = -rowIdx - 1;
      if (colsToRedealFrom[rowIdx] + 1 < this.numCols) {
        for (colIdx = _n = _ref6 = colsToRedealFrom[rowIdx] + 1, _ref7 = this.numCols - 1; _ref6 <= _ref7 ? _n <= _ref7 : _n >= _ref7; colIdx = _ref6 <= _ref7 ? ++_n : --_n) {
          cardId = deck.getNextCard();
          if (cardId >= 0) {
            this.board[rowIdx][colIdx] = cardId;
          }
        }
      }
    }
    return true;
  };

  GameBoard.prototype.getCardId = function(rowIdx, colIdx) {
    return this.board[rowIdx][colIdx];
  };

  GameBoard.prototype.getCardFileName = function(rowIdx, colIdx) {
    var cardId;
    cardId = this.board[rowIdx][colIdx];
    return this.playingCards.getCardFileName(cardId);
  };

  GameBoard.prototype.getCardToLeftInfo = function(cardId) {
    var cardIdx, chkCardId, row, rowIdx, _i, _j, _len, _len1, _ref;
    _ref = this.board;
    for (rowIdx = _i = 0, _len = _ref.length; _i < _len; rowIdx = ++_i) {
      row = _ref[rowIdx];
      for (cardIdx = _j = 0, _len1 = row.length; _j < _len1; cardIdx = ++_j) {
        chkCardId = row[cardIdx];
        if (chkCardId === cardId) {
          if (cardIdx === 0) {
            return [-1, rowIdx, cardIdx];
          }
          return [this.board[rowIdx][cardIdx - 1], rowIdx, cardIdx];
        }
      }
    }
    return [-2, 0, 0];
  };

  GameBoard.prototype.getLocnOfCard = function(cardId) {
    var chkCardId, colIdx, row, rowIdx, _i, _j, _len, _len1, _ref;
    _ref = this.board;
    for (rowIdx = _i = 0, _len = _ref.length; _i < _len; rowIdx = ++_i) {
      row = _ref[rowIdx];
      for (colIdx = _j = 0, _len1 = row.length; _j < _len1; colIdx = ++_j) {
        chkCardId = row[colIdx];
        if (chkCardId === cardId) {
          return [true, rowIdx, colIdx];
        }
      }
    }
    return [false, 0, 0];
  };

  GameBoard.prototype.moveValidCardToEmptyPlace = function(toCardId) {
    var cardToLeftId, clickedCol, clickedRow, fromCardId, _ref;
    if (toCardId < 0) {
      _ref = this.getCardToLeftInfo(toCardId), cardToLeftId = _ref[0], clickedRow = _ref[1], clickedCol = _ref[2];
      if (cardToLeftId === -1) {
        return ["select2", 0, 0, clickedRow, clickedCol];
      }
      if (cardToLeftId >= 0) {
        fromCardId = this.playingCards.findNextCardInSameSuit(cardToLeftId);
        if (fromCardId > 0) {
          return this.moveCard(fromCardId, toCardId);
        }
      }
    }
    return ["none", 0, 0, 0, 0];
  };

  GameBoard.prototype.moveCardIfValid = function(fromCardId, toCardId) {
    var cardToLeftId, clickedCol, clickedRow, moveOk, ok, toColIdx, toRowIdx, _ref, _ref1;
    if (toCardId < 0) {
      moveOk = false;
      if (this.playingCards.getCardInfo(fromCardId).rankIdx === this.playingCards.TwoId) {
        _ref = this.getLocnOfCard(toCardId), ok = _ref[0], toRowIdx = _ref[1], toColIdx = _ref[2];
        if (ok && toColIdx === 0) {
          moveOk = true;
        }
      } else {
        _ref1 = this.getCardToLeftInfo(toCardId), cardToLeftId = _ref1[0], clickedRow = _ref1[1], clickedCol = _ref1[2];
        if (cardToLeftId >= 0) {
          if (fromCardId === this.playingCards.findNextCardInSameSuit(cardToLeftId)) {
            moveOk = true;
          }
        }
      }
      if (moveOk) {
        return this.moveCard(fromCardId, toCardId);
      }
    }
    return ["none", 0, 0, 0, 0];
  };

  GameBoard.prototype.moveCard = function(fromCardId, toCardId) {
    var fromColIdx, fromRowIdx, gapId, ok, toColIdx, toRowIdx, _ref, _ref1;
    _ref = this.getLocnOfCard(fromCardId), ok = _ref[0], fromRowIdx = _ref[1], fromColIdx = _ref[2];
    if (ok) {
      _ref1 = this.getLocnOfCard(toCardId), ok = _ref1[0], toRowIdx = _ref1[1], toColIdx = _ref1[2];
      if (ok) {
        gapId = this.board[toRowIdx][toColIdx];
        this.board[toRowIdx][toColIdx] = this.board[fromRowIdx][fromColIdx];
        this.board[fromRowIdx][fromColIdx] = gapId;
        return ["ok", fromRowIdx, fromColIdx, toRowIdx, toColIdx];
      }
    }
    return ["none", 0, 0, 0, 0];
  };

  GameBoard.prototype.getCardName = function(cardId) {};

  GameBoard.prototype.debugDump = function(debugStr) {
    var cardInfo, col, row, rowStr, _i, _j, _ref, _ref1, _results;
    console.log(debugStr);
    _results = [];
    for (row = _i = 0, _ref = this.numRows - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; row = 0 <= _ref ? ++_i : --_i) {
      rowStr = "";
      for (col = _j = 0, _ref1 = this.numCols - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; col = 0 <= _ref1 ? ++_j : --_j) {
        cardInfo = this.playingCards.getCardInfo(this.getCardId(row, col));
        rowStr += cardInfo.cardShortName + " ";
      }
      _results.push(console.log(rowStr));
    }
    return _results;
  };

  return GameBoard;

})();
