// Generated by CoffeeScript 1.12.7
var GameBoard;

GameBoard = (function() {
  GameBoard.prototype.numRows = 4;

  GameBoard.prototype.numCols = 13;

  function GameBoard(playingCards) {
    this.playingCards = playingCards;
    this.board = [];
    this.turns = 0;
  }

  GameBoard.prototype.copy = function(copyFrom) {
    var boardRow, col, i, j, ref, ref1, row;
    this.board = [];
    for (row = i = 0, ref = this.numRows - 1; 0 <= ref ? i <= ref : i >= ref; row = 0 <= ref ? ++i : --i) {
      boardRow = [];
      for (col = j = 0, ref1 = this.numCols - 1; 0 <= ref1 ? j <= ref1 : j >= ref1; col = 0 <= ref1 ? ++j : --j) {
        boardRow.push(copyFrom.board[row][col]);
      }
      this.board.push(boardRow);
    }
    this.turns = copyFrom.turns;
    return true;
  };

  GameBoard.prototype.deal = function() {
    var boardRow, col, i, j, ref, ref1, row;
    this.board = [];
    this.playingCards.startDeal();
    for (row = i = 0, ref = this.numRows - 1; 0 <= ref ? i <= ref : i >= ref; row = 0 <= ref ? ++i : --i) {
      boardRow = [];
      for (col = j = 0, ref1 = this.numCols - 1; 0 <= ref1 ? j <= ref1 : j >= ref1; col = 0 <= ref1 ? ++j : --j) {
        boardRow.push(this.playingCards.getNextCard());
      }
      this.board.push(boardRow);
    }
    return true;
  };

  GameBoard.prototype.removeAces = function() {
    var cardId, colIdx, gapCardId, i, ref, results, rowIdx;
    gapCardId = -1;
    results = [];
    for (rowIdx = i = 0, ref = this.numRows - 1; 0 <= ref ? i <= ref : i >= ref; rowIdx = 0 <= ref ? ++i : --i) {
      results.push((function() {
        var j, ref1, results1;
        results1 = [];
        for (colIdx = j = 0, ref1 = this.numCols - 1; 0 <= ref1 ? j <= ref1 : j >= ref1; colIdx = 0 <= ref1 ? ++j : --j) {
          cardId = this.board[rowIdx][colIdx];
          if (this.playingCards.getCardInfo(cardId).rankIdx === this.playingCards.AceId) {
            this.board[rowIdx][colIdx] = gapCardId;
            results1.push(gapCardId -= 1);
          } else {
            results1.push(void 0);
          }
        }
        return results1;
      }).call(this));
    }
    return results;
  };

  GameBoard.prototype.redeal = function() {
    var cardId, cardInfo, colIdx, colsToRedealFrom, deck, i, j, k, l, m, n, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, rowIdx, suitIdxForRow;
    colsToRedealFrom = [];
    for (rowIdx = i = 0, ref = this.numRows - 1; 0 <= ref ? i <= ref : i >= ref; rowIdx = 0 <= ref ? ++i : --i) {
      suitIdxForRow = -1;
      for (colIdx = j = 0, ref1 = this.numCols - 1; 0 <= ref1 ? j <= ref1 : j >= ref1; colIdx = 0 <= ref1 ? ++j : --j) {
        cardId = this.board[rowIdx][colIdx];
        cardInfo = this.playingCards.getCardInfo(cardId);
        if (colIdx === 0) {
          suitIdxForRow = cardInfo.suitIdx;
        }
        if (cardInfo.isGap || cardInfo.rankIdx - 1 !== colIdx || cardInfo.suitIdx !== suitIdxForRow) {
          colsToRedealFrom.push(colIdx);
          break;
        }
      }
      console.log(colsToRedealFrom[colsToRedealFrom.length - 1]);
    }
    deck = new PlayingCards();
    deck.empty();
    for (rowIdx = k = 0, ref2 = this.numRows - 1; 0 <= ref2 ? k <= ref2 : k >= ref2; rowIdx = 0 <= ref2 ? ++k : --k) {
      for (colIdx = l = ref3 = colsToRedealFrom[rowIdx], ref4 = this.numCols - 1; ref3 <= ref4 ? l <= ref4 : l >= ref4; colIdx = ref3 <= ref4 ? ++l : --l) {
        cardId = this.board[rowIdx][colIdx];
        if (cardId >= 0) {
          deck.addCard(cardId);
        }
      }
    }
    deck.shuffle();
    deck.startDeal();
    for (rowIdx = m = 0, ref5 = this.numRows - 1; 0 <= ref5 ? m <= ref5 : m >= ref5; rowIdx = 0 <= ref5 ? ++m : --m) {
      this.board[rowIdx][colsToRedealFrom[rowIdx]] = -rowIdx - 1;
      if (colsToRedealFrom[rowIdx] + 1 < this.numCols) {
        for (colIdx = n = ref6 = colsToRedealFrom[rowIdx] + 1, ref7 = this.numCols - 1; ref6 <= ref7 ? n <= ref7 : n >= ref7; colIdx = ref6 <= ref7 ? ++n : --n) {
          cardId = deck.getNextCard();
          if (cardId >= 0) {
            this.board[rowIdx][colIdx] = cardId;
          }
        }
      }
    }
    this.turns += 1;
    return true;
  };

  GameBoard.prototype.getCardId = function(rowIdx, colIdx) {
    return this.board[rowIdx][colIdx];
  };

  GameBoard.prototype.getCardFileName = function(rowIdx, colIdx) {
    var cardId;
    cardId = this.board[rowIdx][colIdx];
    return this.playingCards.getCardFileName(cardId);
  };

  GameBoard.prototype.getCardToLeftInfo = function(cardId) {
    var cardIdx, chkCardId, i, j, len, len1, ref, row, rowIdx;
    ref = this.board;
    for (rowIdx = i = 0, len = ref.length; i < len; rowIdx = ++i) {
      row = ref[rowIdx];
      for (cardIdx = j = 0, len1 = row.length; j < len1; cardIdx = ++j) {
        chkCardId = row[cardIdx];
        if (chkCardId === cardId) {
          if (cardIdx === 0) {
            return [-1, rowIdx, cardIdx];
          }
          return [this.board[rowIdx][cardIdx - 1], rowIdx, cardIdx];
        }
      }
    }
    return [-2, 0, 0];
  };

  GameBoard.prototype.getLocnOfCard = function(cardId) {
    var chkCardId, colIdx, i, j, len, len1, ref, row, rowIdx;
    ref = this.board;
    for (rowIdx = i = 0, len = ref.length; i < len; rowIdx = ++i) {
      row = ref[rowIdx];
      for (colIdx = j = 0, len1 = row.length; j < len1; colIdx = ++j) {
        chkCardId = row[colIdx];
        if (chkCardId === cardId) {
          return [true, rowIdx, colIdx];
        }
      }
    }
    return [false, 0, 0];
  };

  GameBoard.prototype.getEmptySquares = function() {
    var chkCardId, colIdx, emptySqList, i, j, len, len1, ref, row, rowIdx;
    emptySqList = [];
    ref = this.board;
    for (rowIdx = i = 0, len = ref.length; i < len; rowIdx = ++i) {
      row = ref[rowIdx];
      for (colIdx = j = 0, len1 = row.length; j < len1; colIdx = ++j) {
        chkCardId = row[colIdx];
        if (chkCardId < 0) {
          emptySqList.push([rowIdx, colIdx]);
        }
      }
    }
    return emptySqList;
  };

  GameBoard.prototype.getValidMovesForEmptySq = function(toCardId) {
    var cardToLeftId, clickedCol, clickedRow, i, nextCard, ref, suitIdx, validMoves;
    validMoves = [];
    ref = this.getCardToLeftInfo(toCardId), cardToLeftId = ref[0], clickedRow = ref[1], clickedCol = ref[2];
    if (clickedCol === 0) {
      for (suitIdx = i = 0; i <= 3; suitIdx = ++i) {
        validMoves.push([this.playingCards.getCardId(suitIdx, this.playingCards.TwoId), toCardId]);
      }
    } else if (cardToLeftId !== -1) {
      nextCard = this.playingCards.findNextCardInSameSuit(cardToLeftId);
      if (nextCard !== -1) {
        validMoves.push([nextCard, toCardId]);
      }
    }
    return validMoves;
  };

  GameBoard.prototype.moveValidCardToEmptyPlace = function(toCardId) {
    var cardToLeftId, clickedCol, clickedRow, fromCardId, ref;
    if (toCardId < 0) {
      ref = this.getCardToLeftInfo(toCardId), cardToLeftId = ref[0], clickedRow = ref[1], clickedCol = ref[2];
      if (cardToLeftId === -1) {
        return ["select2", 0, 0, clickedRow, clickedCol];
      }
      if (cardToLeftId >= 0) {
        fromCardId = this.playingCards.findNextCardInSameSuit(cardToLeftId);
        if (fromCardId > 0) {
          return this.moveCard(fromCardId, toCardId);
        }
      }
    }
    return ["none", 0, 0, 0, 0];
  };

  GameBoard.prototype.moveCardIfValid = function(fromCardId, toCardId) {
    var cardToLeftId, clickedCol, clickedRow, moveOk, ok, ref, ref1, toColIdx, toRowIdx;
    if (toCardId < 0) {
      moveOk = false;
      if (this.playingCards.getCardInfo(fromCardId).rankIdx === this.playingCards.TwoId) {
        ref = this.getLocnOfCard(toCardId), ok = ref[0], toRowIdx = ref[1], toColIdx = ref[2];
        if (ok && toColIdx === 0) {
          moveOk = true;
        }
      } else {
        ref1 = this.getCardToLeftInfo(toCardId), cardToLeftId = ref1[0], clickedRow = ref1[1], clickedCol = ref1[2];
        if (cardToLeftId >= 0) {
          if (fromCardId === this.playingCards.findNextCardInSameSuit(cardToLeftId)) {
            moveOk = true;
          }
        }
      }
      if (moveOk) {
        return this.moveCard(fromCardId, toCardId);
      }
    }
    return ["none", 0, 0, 0, 0];
  };

  GameBoard.prototype.moveCard = function(fromCardId, toCardId) {
    var fromColIdx, fromRowIdx, gapId, ok, ref, ref1, toColIdx, toRowIdx;
    ref = this.getLocnOfCard(fromCardId), ok = ref[0], fromRowIdx = ref[1], fromColIdx = ref[2];
    if (ok) {
      ref1 = this.getLocnOfCard(toCardId), ok = ref1[0], toRowIdx = ref1[1], toColIdx = ref1[2];
      if (ok) {
        gapId = this.board[toRowIdx][toColIdx];
        this.board[toRowIdx][toColIdx] = this.board[fromRowIdx][fromColIdx];
        this.board[fromRowIdx][fromColIdx] = gapId;
        return ["ok", fromRowIdx, fromColIdx, toRowIdx, toColIdx];
      }
    }
    return ["none", 0, 0, 0, 0];
  };

  GameBoard.prototype.getCardName = function(cardId) {};

  GameBoard.prototype.debugDump = function(debugStr) {
    var cardInfo, col, i, j, ref, ref1, results, row, rowStr;
    console.log(debugStr);
    results = [];
    for (row = i = 0, ref = this.numRows - 1; 0 <= ref ? i <= ref : i >= ref; row = 0 <= ref ? ++i : --i) {
      rowStr = "";
      for (col = j = 0, ref1 = this.numCols - 1; 0 <= ref1 ? j <= ref1 : j >= ref1; col = 0 <= ref1 ? ++j : --j) {
        cardInfo = this.playingCards.getCardInfo(this.getCardId(row, col));
        rowStr += cardInfo.cardShortName + " ";
      }
      results.push(console.log(rowStr));
    }
    return results;
  };

  return GameBoard;

})();

//# sourceMappingURL=GameBoard.js.map
