// Generated by CoffeeScript 1.6.3
var KingsGame;

KingsGame = (function() {
  function KingsGame() {
    this.playingCards = new PlayingCards();
    this.gameBoard = new GameBoard();
    this.displayBoard = new DisplayBoard(this.selCellCallback, this.dragCellCallback, this.selCompleteCallback, this.playingCards, false);
  }

  KingsGame.prototype.start = function() {
    var board, cardId, colIdx, row, rowIdx, _i, _j, _len, _len1;
    this.gameBoard.deal(this.playingCards);
    board = this.gameBoard.getBoard();
    for (rowIdx = _i = 0, _len = board.length; _i < _len; rowIdx = ++_i) {
      row = board[rowIdx];
      for (colIdx = _j = 0, _len1 = row.length; _j < _len1; colIdx = ++_j) {
        cardId = row[colIdx];
        if (this.playingCards.getCardInfo(cardId).rankIdx === 0) {
          board[rowIdx][colIdx] = -1;
        }
      }
    }
    return this.playGame();
  };

  KingsGame.prototype.playGame = function() {
    console.log("Playing Kings");
    return this.displayBoard.showGameState(this.gameBoard);
  };

  return KingsGame;

})();
