// Generated by CoffeeScript 1.6.3
var PlayingCards;

PlayingCards = (function() {
  PlayingCards.prototype.cardsInDeck = 52;

  PlayingCards.prototype.cardsInSuit = 13;

  PlayingCards.prototype.suitNames = ['club', 'diamond', 'heart', 'spade'];

  PlayingCards.prototype.rankNames = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'Jack', 'Queen', 'King'];

  PlayingCards.prototype.dealNextIdx = 0;

  function PlayingCards() {
    this.deck = this.createUnsorted();
    this.deck = this.shuffle(this.deck);
  }

  PlayingCards.prototype.createUnsorted = function() {
    var deck, _i, _ref, _results;
    deck = (function() {
      _results = [];
      for (var _i = 0, _ref = this.cardsInDeck - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; 0 <= _ref ? _i++ : _i--){ _results.push(_i); }
      return _results;
    }).apply(this);
    return deck;
  };

  PlayingCards.prototype.getCardInfo = function(cardId) {
    var cardInfo, rankIdx, suitIdx, suitName;
    suitIdx = Math.floor(cardId / this.cardsInSuit);
    suitName = this.suitNames[suitIdx];
    rankIdx = cardId % this.cardsInSuit;
    cardInfo = {
      suitIdx: suitIdx,
      suitName: suitName,
      rankIdx: rankIdx,
      rankName: this.rankNames[rankIdx],
      cardFileNameSvg: "card_" + (rankIdx + 1) + "_" + suitName + ".svg",
      cardFileNamePng: "card_" + (rankIdx + 1) + "_" + suitName + ".png"
    };
    return cardInfo;
  };

  PlayingCards.prototype.getCardFileName = function(cardId, useSvg) {
    if (cardId === -1) {
      return "card_empty" + (useSvg ? ".svg" : ".png");
    }
    if (useSvg) {
      return this.getCardInfo(cardId).cardFileNameSvg;
    }
    return this.getCardInfo(cardId).cardFileNamePng;
  };

  PlayingCards.prototype.shuffle = function(deck) {
    var i, j, _i, _ref, _ref1;
    for (i = _i = _ref = deck.length - 1; _ref <= 1 ? _i <= 1 : _i >= 1; i = _ref <= 1 ? ++_i : --_i) {
      j = Math.floor(Math.random() * (i + 1));
      _ref1 = [deck[j], deck[i]], deck[i] = _ref1[0], deck[j] = _ref1[1];
    }
    return deck;
  };

  PlayingCards.prototype.startDeal = function() {
    return this.dealNextIdx = 0;
  };

  PlayingCards.prototype.getNextCard = function() {
    var card;
    card = this.deck[this.dealNextIdx];
    this.dealNextIdx += 1;
    this.dealNextIdx = this.dealNextIdx % this.cardsInDeck;
    return card;
  };

  return PlayingCards;

})();
